"""add language to posts

Revision ID: 358d1ccaee0e
Revises: 3d2a6b08cdf0
Create Date: 2021-06-09 23:32:26.544869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358d1ccaee0e'
down_revision = '3d2a6b08cdf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
